rpc: http://rpc.orai.io
lcd: http://lcd.orai.io
chain_id: Oraichain
denom: orai
contract: orai15lv4hxxqew2jhfayfmad7y40zfr8zmgfulqdxj
interval: 10000
ping_interval: 30000
gas_multiplier: 2
gas_price: 0.003
